export enum ModuleItemsMenu {
    UserModule = 'User',
    UserSecurityModule = 'UserSecurity', 
    AuthModule = 'Auth',
    RoleModule = 'Role',
    PermissionModule = 'Permission',
    LogsModule = 'Logs',
    QueuesModule = 'Queues',
    BullBoardModule = 'BullBoard',
    RedisSessionModule = 'RedisSession',
    HealthModule = 'Health',
    ParametersModule = 'Parameters',
    MenuModule = 'Menu',
    FilesModule = 'File',
    EmailModule = 'Email',
    CryptoModule = 'Crypto',
}